### ISSUE TITLE
mispel on mnimal

### ISSUE THREAD

**Issue by rafabene** [fabric8io/kubernetes-zipkin#15]
the readme.md and the artifactid is mispel: mnimal.

**Comment by davsclaus** [comment]
Ah thanks @rafabene you are welcome to do a PR if you fancy that kind of things

**Comment by davsclaus** [comment]
It was much easier to edit the file directly from here on github.

**Comment by iocanel** [comment]
Thanks @rafabene for spotting it and @davsclaus for fixing it.

**Comment by rafabene** [comment]
👍

**Comment by rafabene** [comment]
There's still an issue because now the instruction is not valid anymore: unable to read URL "http://repo1.maven.org/maven2/io/fabric8/zipkin/zipkin-starter-minimal/0.0.4/zipkin-starter-minimal-0.0.4-kubernetes.yml", server reported 404 404 Not Found

I believe that a release 0.0.5 should be made to fix it.

**Comment by rafabene** [comment]
hi @davsclaus Thanks for the commit, but the artifactId and its references among this project should be also fixed: https://github.com/fabric8io/kubernetes-zipkin/blob/master/starter-minimal/pom.xml#L29

Until the release of 0.0.5 version, the readme.md should contain the "wrong" instructions.

Thanks
