### ISSUE TITLE
Error install 0.0.4

### ISSUE THREAD

**Issue by rafabene** [fabric8io/kubernetes-zipkin#17]
There's still an issue because now the instruction is not valid anymore: unable to read URL "http://repo1.maven.org/maven2/io/fabric8/zipkin/zipkin-starter-minimal/0.0.4/zipkin-starter-minimal-0.0.4-kubernetes.yml", server reported 404 404 Not Found

I believe that a release 0.0.5 should be made to fix it.

I'm reporting a new issue to avoid having it marked as fixed in #15

**Comment by iocanel** [comment]
I think its ok now

**Comment by rafabene** [comment]
Anyway, it seems that we will need a 0.0.5 release, otherwise who follow the readme.md instructions will still face the unable to read URL "http://repo1.maven.org/maven2/io/fabric8/zipkin/zipkin-starter-minimal/0.0.4/zipkin-starter-minimal-0.0.4-kubernetes.yml", server reported 404 404 Not Found

**Comment by iocanel** [comment]
The readme.md has been updated to point to the 0.0.7 artifacts, but the readme.md inside the release tarball is still referring to the old artifacts. 

@rawlingsj: does the release plugin we are using support anything like that? If not could we do something like this through the release.groovy?

**Comment by rafabene** [comment]
Oh! That's true @iocanel . I haven't see the 0.0.7 release until now.

Thanks. So I believe that this issue should be closed since it's already fixed. Unless you found another issue.

**Comment by iocanel** [comment]
Ok, I'll close it for now and I'll create a new one for automatically bumping version in the readme.md.
