### ISSUE TITLE
Zipkin 0.0.7 RC uses a non existing image fabric8/zipkin-mysql:1.39.3

### ISSUE THREAD

**Issue by rafabene** [fabric8io/kubernetes-zipkin#23]
I tried zipkin 0.0.7 minimal today and the RC refers to a non existent image fabric8/zipkin-mysql:1.39.3

So the readme.md instructions for 0.0.7 still failing

**Comment by rafabene** [comment]
Check http://repo1.maven.org/maven2/io/fabric8/zipkin/zipkin-starter-minimal/0.0.7/zipkin-starter-minimal-0.0.7-kubernetes.yml

**Comment by iocanel** [comment]
Release 0.0.8 is out and also fabric8/zipkin-mysql:0.0.8 is in docker hub.

Now, we need to update docs and also add some automated integration tests, to prevent such issues.

**Comment by iocanel** [comment]
docs updated integration tests have been added.

**Comment by iocanel** [comment]
@rafabene: thanks!

**Comment by rafabene** [comment]
@iocanel Thanks you too.
