### ISSUE TITLE
zipkin-query with 2 services

### ISSUE THREAD

**Issue by rafabene** [fabric8io/kubernetes-zipkin#26]
I'm not sure if this is an issue or not, but actually the rc/zipkin-query has two services: svc/zipkin-query (exposing 9411) and svc/zipkin-query-admin (exposing 9901).

I'm not sure if this is really necessary.

```
svc/zipkin-query - 172.30.166.5:9411
  rc/zipkin-query runs openzipkin/zipkin-query:1.39.3
    rc/zipkin-query created 18 hours ago - 1 pod
  exposed by route/zipkin-query

svc/zipkin-query-admin - 172.30.26.80:9901
  rc/zipkin-query runs openzipkin/zipkin-query:1.39.3
    rc/zipkin-query created 18 hours ago - 1 pod
```

**Comment by adriancole** [comment]
recent versions of zipkin don't expose a separate admin port anyway, so we
should stick with 9411. Note that in docker, we expose 8080, too (mapping
to 9411), as that's what zipkin-web used to listen on.

**Comment by iocanel** [comment]
That's great I am going to remove the port asap.
