### ISSUE TITLE
zipkin-web is gone

### ISSUE THREAD

**Issue by eirslett** [fabric8io/kubernetes-zipkin#5]
The UI is now hosted directly from zipkin-query.

**Comment by iocanel** [comment]
@eirslett I see that zipkin-web was included in the 1.39.3 release and I still see it in the trunk. Can you please provide some more details about it, cause I think I missed something :-)

**Comment by eirslett** [comment]
Yes. The role of zipkin-web was earlier to make requests to the zipkin-query API, and then render the results to HTML on the server side. What happened, is that zipkin-ui (html/css/javascript) was refactored into its own module, and is now a pure client-side, single-page web application. It consumes the zipkin-qiuery HTTP API directly, so we figured it's easier if zipkin-query hosts the web UI as well; then we'll have one less application to deploy. So basically, zipkin-web has no purpose.

zipkin-web was rewritten, so that it now acts as a pure http reverse proxy; much like haproxy or nginx. [This line](https://github.com/openzipkin/zipkin/blob/master/zipkin-web/src/main/scala/com/twitter/zipkin/web/Main.scala#L67) is the only important line in zipkin-web, which sets up a http proxy client and hooks it up to the server. The rest of the code in that module is boilerplate.

The reason zipkin-web still exists, is for people who deploy zipkin with some automated script, and only bump the zipkin version number between deploys. (Basically provide a smoother depcretation/migration path)
It's only a pure, stupid http proxy by now, so all zipkin deployments should be migrated to serving zipkin-query directly to end users.

**Comment by iocanel** [comment]
@eirslett: Thank you so much for the details.

**Comment by iocanel** [comment]
Removed the web module and added a section in the readme to describe where the console now lives.

Thanks again @eirslett for taking the time and explain.
