### ISSUE TITLE
MySQL error when searching for traces.

### ISSUE THREAD

**Issue by iocanel** [fabric8io/kubernetes-zipkin#59]
org.mariadb.jdbc.internal.util.dao.QueryException: Expression #1 of ORDER BY clause is not in SELECT list, references column 'zipkin.zipkin_spans.start_ts' which is not in SELECT list; this is incompatible with DISTINCT
Query is : select distinct `zipkin_spans`.`trace_id` from `zipkin_spans` join `zipkin_annotations` on (`zipkin_spans`.`trace_id` = `zipkin_annotations`.`trace_id` and `zipkin_spans`.`id` = `zipkin_annotations`.`span_id`) where (`zipkin_spans`.`start_ts` between 1475757274431000 and 1475760874431000 and `zipkin_annotations`.`endpoint_service_name` = 'helloworld') order by `zipkin_spans`.`start_ts` desc limit 10

**Comment by iocanel** [comment]
The issue has to do with the default settings of mysql post 5.7. 

The [zipkin mysql docs](https://github.com/openzipkin/zipkin/tree/master/zipkin-storage/mysql) propose a solution, that we need to apply, preferable without having to create an image of our own.

**Comment by adriancole** [comment]
Closed because fixed?

**Comment by iocanel** [comment]
@adriancole: yes, adding:

    [mysqld]
    sql-mode=""

did the trick.
