### ISSUE TITLE
Add links for newbies

### ISSUE THREAD

**Issue by adriancole** [fabric8io/kubernetes-zipkin#62]
We are getting more folks asking about kubernetes-zipkin on gitter, but most of us are unfamiliar with kubernetes (at the moment). https://gitter.im/openzipkin/zipkin

Is there something we could do in this README to help folks who've never used kubernetes before...
- understand what url zipkin would be listening on (ex for instrumentation or the UI)?
- know which chat they should go to if they are trying to figure out kubernetes
- know which chat they should go to if debugging this project

I don't know if the two latter concerns have a good home, just trying to figure out a way to do something besides wait of @iocanel to wake up :)

**Comment by luukhoai** [comment]
Hi, This is Silver.
Please give me some instruction that kubernetes send a zipkin_span into zipkin, and display in the UI.
Thank you so much.

**Comment by iocanel** [comment]
I completely missed this one! I'll add something asap.

**Comment by adriancole** [comment]
thanks @iocanel
