### ISSUE TITLE
mvn fabric8:apply -pl starter-mysql fails

### ISSUE THREAD

**Issue by seansong2004** [fabric8io/kubernetes-zipkin#63]
[ERROR] Could not find goal 'apply' in plugin io.fabric8:fabric8-maven-plugin:3.1.63 among available goals app-catalog, build, cluster-start, cluster-stop, debug, deploy, distro, helm, helm-index, help, import, install, log, manifest-index, push, resource, resource-apply, run, setup, start, stop, undeploy, watch -> [Help 1]

**Comment by iocanel** [comment]
We've moved to f-m-p 3.x but our documentation is out of sync. I'll update the docs asap.

**Comment by davsclaus** [comment]
Thanks for the PR from @levackt we have the docs updated now
